# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

update_fastlane

platform :ios do
  desc "Description of what the lane does"
  lane :release do
    ensure_git_branch
    version = version_get_podspec(path: "AVPlayerDNAPlugin.podspec")
    changelog = prompt(text: "Changelog: ", multi_line_end_keyword: "END")

    github_token = ENV['GITHUB_TOKEN']
    if !github_token || github_token.empty?
      github_token = prompt(text: "Please enter your GitHub token: ")
    end

    github_release = set_github_release(
      repository_name: "streamroot/avplayer-dna-plugin",
      api_token: github_token,
      name: version,
      tag_name: "v#{version}",
      description: changelog,
      commitish: "master"
    )
    sh("git fetch --tags")
    pod_push(allow_warnings: true, verbose: true)
  end
end
